version: '3.9'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "443:443"

    volumes:
      - ./nginx-config/conf.d:/etc/nginx/nginx.conf:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./crt:/etc/nginx/ssl:ro 
