project: default
source:
  repoURL: 'https://github.com/MhmdAbdo74/fixed-solutions-tasks-22.git'
  path: mychart
  targetRevision: HEAD
destination:
  server: 'https://kubernetes.default.svc'
  namespace: helm-chart
syncPolicy:
  syncOptions:
    - CreateNamespace=true
  automated:
     selfHeal: true
     prune: true
