apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: helm-chart
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewogICAgImF1dGhzIjogewogICAgICAgICAgICAiaHR0cHM6Ly9pbmRleC5kb2NrZXIuaW8vdjEvIjogewogICAgICAgICAgICAgICAgICAgICJhdXRoIjogImJXOW9ZVzFsWkRJd01qRXhOak0zTUVCbmJXRnBiQzVqYjIwNmNHVlhTQ00wTDFna0wwd2taMlJNIiwKICAgICAgICAgICAgICAgICAgICAiZW1haWwiOiAibW9oYW1lZDIwMjExNjM3MEBnbWFpbC5jb20iCiAgICAgICAgICAgIH0KICAgIH0KfSAgICA=
