version: '3.8'
services:
  # MySQL Service
  mysql:
    image: mysql:8
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=flask_app_password
      - MYSQL_USER=flask_app_user
      - MYSQL_DATABASE=flask_app_db
      - MYSQL_PASSWORD=flask_app_password

  # Flask App Service (put env variable defined in app with env value defined in database service)
  flaskapp:
    image: mohamed222/fixed-solution
    container_name: flask_app
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=flask_app_user
      - MYSQL_PASSWORD=flask_app_password
      - MYSQL_DBNAME=flask_app_db
      - VIRTUAL_HOST=flaskapp
      - VIRTUAL_PORT=5000
      - VIRTUAL_PATH=/
      - CERT_NAME=mywebsite

    ports:
      - 5000:5000
    restart: always
    depends_on:
      - mysql

  # phpMyAdmin Service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql
      PMA_USER: flask_app_user
      PMA_PASSWORD: flask_app_password


    ports:
      - "8000:80"
    depends_on:
      - mysql
