{{- if .Values.HPA.enabled  -}}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
 {{- with .Values.HPA }} 
metadata:
  name: {{ .name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ $.Values.flaskApp.name }}
  minReplicas: {{ .minReplicas }}
  maxReplicas: {{ .maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
 {{- end  }}
{{- end }}        
