apiVersion: apps/v1
kind: StatefulSet
      {{- with .Values.mysqlstatefulset }}
metadata:
  name: {{ .name }}
  labels:
    app: {{ .selector }}
spec:
  replicas: {{ .replicas }}
  serviceName: {{ .service.name }}
  selector:
    matchLabels:
      app: {{ .selector }}
  template:
    metadata:
      labels:
        app: {{ .selector }}
    spec:
      containers:
      - name: mysql
        image: mysql:8
        ports:
        - containerPort: {{ .port }}
        env:
         {{- with $.Values.mysqlsecrets }}
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .name }}
              key: root-password
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: {{ .name }}
              key: user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .name }}
              key: password
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: {{ .name }}
              key: database
         {{- end }}     
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: {{ $.Values.pvc.name }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .service.name }}
spec:
  selector:
    app: {{ .selector  }}
  ports:
    - protocol: TCP
      port: {{ .port }}
      targetPort: {{ .port }}
      {{- end }}    