apiVersion: v1
kind: PersistentVolume
{{- with .Values.pv }}
metadata:
  name: {{ .name }}
spec:
  capacity:
    storage: {{ .storage }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .path  }}
{{- end }}    