apiVersion: v1
kind: PersistentVolumeClaim
{{- with .Values.pvc }}
metadata:
  name: {{ .name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage:  {{ .storage }}
{{- end  }}